export const PRICING_PLANS = [
  {
    code: "starter",
    name: "Starter",
    priceMonthlyUsd: 29,
    highlighted: false,
    description: "Best for small tour operators getting started.",
    cta: "Start Free Trial",
    features: [
      "Professional tourism website + CMS",
      "Manage tours, bookings, and inquiries",
      "AI-generated blogs and tour descriptions",
      "Basic chatbot support",
      "Payment automation",
      "1 connected social account",
    ],
    limits: {
      aiGenerations: 20,
      chatbotInteractions: 50,
      socialAccounts: 1,
    },
  },
  {
    code: "growth",
    name: "Growth",
    priceMonthlyUsd: 79,
    highlighted: true,
    description: "Best for operators who want more bookings from social and lead capture.",
    cta: "Most Popular",
    features: [
      "Everything in Starter",
      "Instagram and Facebook automation",
      "AI captions and hashtags",
      "Lead inbox and qualification flows",
      "Email follow-up automation",
      "Review automation",
      "Payment automation",
      "Visa and travel documentation assistant",
    ],
    limits: {
      aiGenerations: 200,
      chatbotInteractions: 500,
      socialAccounts: 2,
    },
  },
  {
    code: "pro",
    name: "Pro",
    priceMonthlyUsd: 199,
    highlighted: false,
    description: "Best for serious tour companies ready to scale across channels.",
    cta: "Scale Faster",
    features: [
      "Everything in Growth",
      "WhatsApp automation",
      "Unified inbox operations",
      "Campaign automation",
      "Guide & driver management",
      "Accommodation coordination",
      "Airport pickup coordination",
      "Repeat customer automation",
      "Payment automation",
      "Advanced analytics and priority support",
    ],
    limits: {
      aiGenerations: 1000,
      chatbotInteractions: 3000,
      socialAccounts: 10,
    },
  },
  {
    code: "enterprise",
    name: "Enterprise",
    priceMonthlyUsd: 399,
    highlighted: false,
    description: "Large travel brands with partner operations and advanced coordination",
    cta: "Talk to Sales",
    features: [
      "Everything in Pro",
      "Partner portal",
      "Dynamic pricing engine",
      "Multi-language AI assistant",
      "Advanced operational controls",
      "Enterprise relationship management",
    ],
    limits: {
      aiGenerations: 5000,
      chatbotInteractions: 10000,
      socialAccounts: 50,
    },
  },
];

export const FEATURE_PLAN_REQUIREMENTS = {
  "social-accounts": "growth",
  "social-posts": "growth",
  "lead-inbox": "growth",
  repurposing: "growth",
  "review-automation": "growth",
  "payment-automation": "starter",
  "travel-documentation-assistant": "growth",
  campaigns: "pro",
  "guide-driver-management": "pro",
  "accommodation-coordination": "pro",
  "airport-pickup-coordination": "pro",
  "partner-portal": "enterprise",
  "dynamic-pricing-engine": "enterprise",
  "multi-language-ai-assistant": "enterprise",
  "repeat-customer-automation": "pro",
  "whatsapp-automation": "pro",
};

export const getPricingPlan = (planCode = "starter") =>
  PRICING_PLANS.find((plan) => plan.code === planCode) || PRICING_PLANS[0];

