export const HOME_PAGE_DEFAULT = {
  pageType: "home",
  slug: "/",
  title: "Home",
  status: "published",
  seo: {
    title: "Tanzania Luxury Safaris & Adventure Tours",
    description:
      "MAZ Expeditions offers premium safari experiences in Serengeti, Ngorongoro, and Zanzibar. Book your dream African holiday today.",
    keywords: [
      "Safari",
      "Tanzania",
      "Serengeti",
      "Zanzibar",
      "Luxury Travel",
      "MAZ Expeditions",
    ],
  },
  sections: [
    {
      type: "hero",
      variant: "cinematic",
      order: 1,
      enabled: true,
      dataConfig: {
        backgroundMediaType: "video",
      },
      contentConfig: {
        eyebrow: "Karibu Maz",
        headlineScript: "Expeditions",
        primaryCtaLabel: "START PLANNING NOW",
        primaryCtaHref: "/plan-my-trip",
        secondaryCtaLabel: "Explore All Packages",
        secondaryCtaHref: "/packages",
      },
      styleConfig: {
        minHeight: "screen",
      },
    },
    {
      type: "trending",
      variant: "default",
      order: 2,
      enabled: true,
      dataConfig: {},
      contentConfig: {},
      styleConfig: {},
    },
    {
      type: "about",
      variant: "welcome",
      order: 3,
      enabled: true,
      dataConfig: {},
      contentConfig: {},
      styleConfig: {},
    },
    {
      type: "featuredPackages",
      variant: "popular-grid",
      order: 4,
      enabled: true,
      dataConfig: {
        source: "tours",
        limit: 6,
      },
      contentConfig: {
        prefixLabel: "Our",
        scriptLabel: "popular",
        suffixLabel: "Expeditions",
      },
      styleConfig: {},
    },
    {
      type: "groupTours",
      variant: "default",
      order: 5,
      enabled: true,
      dataConfig: {
        source: "group-tours",
      },
      contentConfig: {},
      styleConfig: {},
    },
    {
      type: "blogPreview",
      variant: "category-grid",
      order: 6,
      enabled: true,
      dataConfig: {
        source: "blogs",
        maxPerCategory: 3,
      },
      contentConfig: {},
      styleConfig: {},
    },
    {
      type: "destinations",
      variant: "quote-list",
      order: 7,
      enabled: true,
      dataConfig: {
        source: "taxonomy-destinations",
      },
      contentConfig: {},
      styleConfig: {},
    },
    {
      type: "testimonials",
      variant: "default",
      order: 8,
      enabled: true,
      dataConfig: {},
      contentConfig: {},
      styleConfig: {},
    },
    {
      type: "cta",
      variant: "trip-cta",
      order: 9,
      enabled: true,
      dataConfig: {},
      contentConfig: {
        heading: "Let's talk about your",
        subheading: "Trip to Africa!",
        description:
          "All our custom itineraries are inspired by our travel experts and positive feedback from past travelers. We're sharing them so you can get a taste of the experience. However, we're flexible and can tailor-make an itinerary just for you. Let us know your preferences, and our safari experts will create a personalized proposal.",
        primaryLabel: "Useful Articles",
        primaryHref: "/blogs",
        secondaryLabel: "Plan My Trip",
        secondaryHref: "/contact",
        backgroundImage:
          "https://images.unsplash.com/photo-1547970810-dc1eac37d174?ixlib=rb-4.0.3&auto=format&fit=crop&w=1920&q=80",
      },
      styleConfig: {},
    },
    {
      type: "logoCloud",
      variant: "default",
      order: 10,
      enabled: true,
      dataConfig: {},
      contentConfig: {},
      styleConfig: {},
    },
  ],
};
