import { jsPDF } from "jspdf";

export const generateQuotePdf = (quote) => {
  const doc = new jsPDF();
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 30;

  // Header / Branding
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42); // Slate 900
  doc.text(quote.title.toUpperCase(), margin, y);
  
  y += 10;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text(`Proposal ID: ${quote._id?.substring(0, 8).toUpperCase()}`, margin, y);
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, pageWidth - margin - 40, y);

  y += 20;
  
  // Traveler Info
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text("PREPARED FOR", margin, y);
  
  y += 7;
  doc.setFont("helvetica", "normal");
  doc.text(`${quote.travelerName}`, margin, y);
  
  // Trip Summary Stats
  doc.setDrawColor(241, 245, 249); // Slate 100
  doc.setLineWidth(0.5);
  doc.line(margin, y + 10, pageWidth - margin, y + 10);
  
  y += 25;
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("DESTINATION", margin, y);
  doc.text("DURATION", margin + 60, y);
  doc.text("TRAVELERS", margin + 110, y);
  
  y += 7;
  doc.setFont("helvetica", "normal");
  doc.text(quote.destinationLabel, margin, y);
  doc.text(`${quote.tripLengthDays} Days`, margin + 60, y);
  doc.text(`${quote.travelerCount} Person(s)`, margin + 110, y);

  y += 20;

  // Summary
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("PROPOSAL SUMMARY", margin, y);
  y += 7;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const splitSummary = doc.splitTextToSize(quote.summary, pageWidth - margin * 2);
  doc.text(splitSummary, margin, y);
  y += (splitSummary.length * 5) + 10;

  // Itinerary
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("ITINERARY OUTLINE", margin, y);
  y += 10;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  
  quote.itineraryOutline.forEach((day) => {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    doc.setDrawColor(226, 232, 240); // Slate 200
    doc.setFillColor(248, 250, 252); // Slate 50
    doc.rect(margin, y - 4, pageWidth - margin * 2, 8, "F");
    doc.text(day, margin + 5, y + 1);
    y += 12;
  });

  y += 10;

  // Pricing
  if (y > 230) {
    doc.addPage();
    y = 20;
  }
  
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("PRICING & INCLUSIONS", margin, y);
  y += 10;
  
  doc.setFontSize(10);
  quote.lineItems.forEach((item) => {
    doc.setFont("helvetica", "bold");
    doc.text(item.label, margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(`${quote.currency} ${item.amount.toLocaleString()}`, pageWidth - margin - 30, y);
    y += 5;
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(item.notes, margin, y);
    y += 7;
    doc.setFontSize(10);
    doc.setTextColor(0);
  });

  doc.setDrawColor(15, 23, 42);
  doc.setLineWidth(1);
  doc.line(margin, y + 5, pageWidth - margin, y + 5);
  
  y += 15;
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("TOTAL PROPOSAL AMOUNT", margin, y);
  doc.text(`${quote.currency} ${quote.totalPrice.toLocaleString()}`, pageWidth - margin - 40, y);

  y += 20;
  doc.setFontSize(9);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(100);
  doc.text(`This quote is valid until ${new Date(quote.validUntil).toLocaleDateString()}.`, margin, y);

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, 285, { align: "center" });
    doc.text("Generated by MAZ Expeditions AI Engine", margin, 285);
  }

  doc.save(`${quote.title.replace(/\s+/g, "_")}_Quote.pdf`);
};
